# Generated by Django 4.0 on 2022-01-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLiente',
            new_name='Clientes',
        ),
    ]
